chains:
  - name: left_arm
    topic: /l_arm_controller/follow_joint_trajectory
    joints:
     - l_shoulder_pan_joint
     - l_shoulder_lift_joint
     - l_upper_arm_roll_joint
     - l_elbow_flex_joint
     - l_forearm_roll_joint
     - l_wrist_flex_joint
     - l_wrist_roll_joint
    planning_group: left_arm
  - name: head
    topic: /head_traj_controller/follow_joint_trajectory
    joints:
     - head_pan_joint
     - head_tilt_joint
duration: 2.0
features:
  checkerboard_finder:
    type: robot_calibration/CheckerboardFinder
    topic: /head_mount_kinect/depth_registered/points
    camera_sensor_name: head_mount_kinect
    chain_sensor_name: left_arm
