chains:
  - name: right_arm
    topic: /r_arm_controller/follow_joint_trajectory
    joints:
     - r_shoulder_pan_joint
     - r_shoulder_lift_joint
     - r_upper_arm_roll_joint
     - r_elbow_flex_joint
     - r_forearm_roll_joint
     - r_wrist_flex_joint
     - r_wrist_roll_joint
    planning_group: right_arm
  - name: head
    topic: /head_traj_controller/follow_joint_trajectory
    joints:
     - head_pan_joint
     - head_tilt_joint
duration: 2.0
features:
  checkerboard_finder:
    type: robot_calibration/CheckerboardFinder
    topic: /head_mount_kinect/depth_registered/points
    camera_sensor_name: head_mount_kinect
    chain_sensor_name: right_arm
